project:
  type: website
  output-dir: docs
  
website:
  title: "JEO-ARKEOLOJI"
  site-url: "https://jeoarkeoloji.github.io/"
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Anasayfa
      - href: projedetay.qmd
        text: Proje Detayları
      - href: amackapsam.qmd
        text: Amaç ve Kapsam     
      - text: Kurullar
        menu:
          - text: "Bilim Kurulu"
            href: bilimkurulu.qmd
          - text: "Düzenleme Kurulu"
            href: duzenlemekurulu.qmd
          - text: "Eğitmenler"
            href: egitmenler.qmd
      - href: hedefkitle.qmd
        text: Hedef Kitle & Kriterler
      - href: program.qmd
        text: Program
      - href: https://docs.google.com/forms/d/e/1FAIpQLSdbzCQkCQYutvDw_QysIinaCJGGkWG308JK8zAM6tJjXRLQRA/viewform
        text: Başvuru
      - href: iletisim.qmd
        text: İletişim
    tools:
      - icon: github
        href: https://github.com/JeoArkeoloji
  page-footer: 
    left: "JEO-ARKEOLOJI &copy; Copyright 2024"
    right: " "
    background: "#593196"

format:
  html:
    theme: Pulse
    css: styles.css
    toc: true

editor: source