project:
  type: website
  output-dir: docs
  
website:
  title: "JEO-ARKEOLOJI"
  navbar:
    left:
      - href: index.qmd
        text: Anasayfa
      - href: projedetay.qmd
        text: Proje Detayları
      - href: amackapsam.qmd
        text: Amaç ve Kapsam     
      - href: kurullar.qmd
        text: Kurullar
      - href: hedefkitle.qmd
        text: Hedef Kitle & Kriterler
      - href: program.qmd
        text: Program
      - href: index.qmd
        text: Başvuru
      - href: iletisim.qmd
        text: İletişim
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/JeoArkeoloji
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, JEO-ARKEOLOJI"

format:
  html:
    theme: Pulse
    toc: true

editor: source